version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: '/home/trainer/Trainer_Storage/image_repositories/weapons'
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /home/trainer/Trainer_Storage/cvat_data
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /home/trainer/Trainer_Storage/image_repositories/weapons
      o: bind
