version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: '/home/ubuntu/image_repositories'
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /home/ubuntu/cvat_data
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /home/ubuntu/image_repositories
      o: bind
