version: '3.3'

services:
  cvat:
    environment:
      ALLOWED_HOSTS: '*'
      UI_SCHEME: http
      UI_HOST: cvat.omnilert.io
      UI_PORT: 8080
      CVAT_SHARE_URL: '/home/ubuntu/image_repositories'
    volumes:
      - cvat_share:/home/django/share:ro
      - cvat_data:/home/django/data
    ports:
      - '80:8080'

volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /home/ubuntu/cvat_data
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /home/ubuntu/image_repositories
      o: bind
