version: '3.3'

services:
  cvat:
    environment:
      ALLOWED_HOSTS: '*'
      UI_SCHEME: http
      UI_HOST: 192.168.1.223
      UI_PORT: 7080
      CVAT_SHARE_URL: '/home/data/image_repositories/weapons'
    volumes:
      - cvat_share:/home/django/share:ro
      - cvat_data:/home/django/data
    ports:
      - '80:8080'
  cvat_proxy:
    environment:
      CVAT_HOST: 192.168.1.223


volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /home/data/cvat_data
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /home/data/image_repositories/weapons
      o: bind
